language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t sunnyguptagg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sunnyguptagg/docker-react npm run test