language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t sunnyguptagg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sunnyguptagg/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker React"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-471473744430"
  bukcet_path: "Docker React"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_ket: "$AWS_SECRET_KEY"
